"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import urlparse

try:
    load_dotenv()
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-arl+6l_7zfkkb3t_4)@vz#(9nh26+ack^dprg&xcb@fr80ritc')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Updated ALLOWED_HOSTS for Railway deployment
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Add Railway domains automatically
RAILWAY_STATIC_URL = os.environ.get('RAILWAY_STATIC_URL', '')
if RAILWAY_STATIC_URL:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL)

# Allow all Railway.app, Render.com, and Vercel domains in production
if not DEBUG:
    ALLOWED_HOSTS.extend([
        '.railway.app',
        '.up.railway.app',
        '.onrender.com',
        '.vercel.app',  # Add Vercel subdomains
        'ecoshop-alpha.store',
        'www.ecoshop-alpha.store',
    ])
else:
    # Local dev
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',         # For React integration
    'rest_framework',      # For creating REST API
    'rest_framework_simplejwt',
    'csp',                 # Content Security Policy
    'shop.apps.ShopConfig', # Our shop application
    'accounts.apps.AccountsConfig',
    'blog.apps.BlogConfig',
]

MIDDLEWARE = [
    'backend.debug_middleware.ExceptionLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add Whitenoise here
    # 'backend.security_middleware.SecurityHeadersMiddleware',  # Custom security headers (DISABLED FOR DEBUG)
    # 'csp.middleware.CSPMiddleware',  # Content Security Policy (DISABLED FOR DEBUG)
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Allow requests from frontend port (3000)
# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = '*'

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://*.up.railway.app',
    'https://*.onrender.com',
    'https://*.vercel.app',
    'https://ecoshop-alpha.vercel.app',
    'https://www.ecoshop-alpha.store',
    'https://ecoshop-alpha.store',
]

CORS_ALLOWED_ORIGINS = [
    'https://ecoshop-alpha.vercel.app',
    'https://www.ecoshop-alpha.store',
    'https://ecoshop-alpha.store',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all in debug mode


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}",
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Allow override via env var (used by api/index.py to point to /tmp in Vercel serverless)
STATIC_ROOT = os.environ.get(
    'DJANGO_STATIC_ROOT',
    os.path.join(BASE_DIR, 'staticfiles')
)

# Additional locations for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend', 'dist'),
] if os.path.exists(os.path.join(BASE_DIR, 'frontend', 'dist')) else []

# Whitenoise for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.WhiteNoiseStorage'  # More resilient for serverless than manifest binary


# ---------------------------------------------------------------------------
# Media / File Storage – Supabase Storage (S3-compatible)
# ---------------------------------------------------------------------------
# Set SUPABASE_URL, SUPABASE_S3_ENDPOINT, SUPABASE_STORAGE_KEY, and
# SUPABASE_STORAGE_BUCKET as environment variables.
# When those vars are absent (local dev without Supabase), fall back to
# the local filesystem so the dev server still works.
# ---------------------------------------------------------------------------
_SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
_SUPABASE_S3_ENDPOINT = os.environ.get(
    'SUPABASE_S3_ENDPOINT',
    f"{_SUPABASE_URL}/storage/v1/s3" if _SUPABASE_URL else ''
)
_SUPABASE_STORAGE_KEY = os.environ.get('SUPABASE_SERVICE_ROLE_KEY', '')
_SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'products')

if _SUPABASE_URL and _SUPABASE_STORAGE_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    # Supabase S3 uses Project Ref as Access Key and Service Role Key as Secret Key
    AWS_ACCESS_KEY_ID = urlparse(_SUPABASE_URL).netloc.split('.')[0] if _SUPABASE_URL else ''
    AWS_SECRET_ACCESS_KEY = _SUPABASE_STORAGE_KEY
    AWS_STORAGE_BUCKET_NAME = _SUPABASE_STORAGE_BUCKET
    AWS_S3_ENDPOINT_URL = _SUPABASE_S3_ENDPOINT
    AWS_S3_REGION_NAME = 'us-east-1'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'

    # Public CDN URL for images served from Supabase Storage
    MEDIA_URL = f"{_SUPABASE_URL}/storage/v1/object/public/{_SUPABASE_STORAGE_BUCKET}/"
    MEDIA_ROOT = ''
else:
    # Local fallback
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Security Settings for Production
if not DEBUG:
    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # SSL/HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (django-csp 4.0+)
CSP = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", "'unsafe-eval'"),
    'style-src': ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com"),
    'font-src': ("'self'", "https://fonts.gstatic.com"),
    'img-src': ("'self'", "data:", "https:"),
    'connect-src': ("'self'", "https://*.onrender.com", "https://*.railway.app", "https://*.supabase.co", "https://*.vercel.app"),
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Log 404s and errors
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
