# Generated by Django 6.0 on 2025-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='Ukraine', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, help_text='e.g., All types, Dry, Oily', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, help_text='e.g., 50 ml', max_length=50),
        ),
    ]
