# Generated by Django 6.0 on 2025-12-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_country_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_category', to='shop.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
